# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\gui\min_win.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    
    camb_imgs_list = []
    score_idices = []
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1299, 732)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.centralWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1279, 712))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(839, 649))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.scrollArea_3 = QtGui.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 412, 442))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents_5)
        self.label_5.setGeometry(QtCore.QRect(50, 50, 151, 231))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_5.raise_()
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_4.addWidget(self.scrollArea_3, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.horizontalLayout.addWidget(self.pushButton_10)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 1, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout.addWidget(self.pushButton_6)
        self.gridLayout_4.addLayout(self.verticalLayout, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(10)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setMargin(10)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 1, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.scrollArea_2 = QtGui.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 839, 566))
        self.scrollAreaWidgetContents_2.setMinimumSize(QtCore.QSize(360, 505))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setMinimumSize(QtCore.QSize(120, 150))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setMinimumSize(QtCore.QSize(120, 150))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setMinimumSize(QtCore.QSize(120, 150))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setMinimumSize(QtCore.QSize(120, 150))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setMinimumSize(QtCore.QSize(120, 150))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setMinimumSize(QtCore.QSize(120, 150))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 5, 1, 1)
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setMinimumSize(QtCore.QSize(120, 150))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 0, 6, 1, 1)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_14.setMinimumSize(QtCore.QSize(120, 150))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 7, 1, 1)
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_15.setMinimumSize(QtCore.QSize(120, 150))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 8, 1, 1)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_16.setMinimumSize(QtCore.QSize(120, 150))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 9, 1, 1)
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_17.setMinimumSize(QtCore.QSize(120, 150))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_18.setMinimumSize(QtCore.QSize(120, 150))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_19.setMinimumSize(QtCore.QSize(120, 150))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 1, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_20.setMinimumSize(QtCore.QSize(120, 150))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_2.addWidget(self.label_20, 1, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_21.setMinimumSize(QtCore.QSize(120, 150))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 1, 4, 1, 1)
        self.label_37 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_37.setMinimumSize(QtCore.QSize(120, 150))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 1, 5, 1, 1)
        self.label_38 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_38.setMinimumSize(QtCore.QSize(120, 150))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 1, 6, 1, 1)
        self.label_39 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_39.setMinimumSize(QtCore.QSize(120, 150))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 1, 7, 1, 1)
        self.label_40 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_40.setMinimumSize(QtCore.QSize(120, 150))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_2.addWidget(self.label_40, 1, 8, 1, 1)
        self.label_41 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_41.setMinimumSize(QtCore.QSize(120, 150))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_2.addWidget(self.label_41, 1, 9, 1, 1)
        self.label_42 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_42.setMinimumSize(QtCore.QSize(120, 150))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_2.addWidget(self.label_42, 2, 0, 1, 1)
        self.label_43 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_43.setMinimumSize(QtCore.QSize(120, 150))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_2.addWidget(self.label_43, 2, 1, 1, 1)
        self.label_44 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_44.setMinimumSize(QtCore.QSize(120, 150))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_2.addWidget(self.label_44, 2, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_45.setMinimumSize(QtCore.QSize(120, 150))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_2.addWidget(self.label_45, 2, 3, 1, 1)
        self.label_46 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_46.setMinimumSize(QtCore.QSize(120, 150))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_2.addWidget(self.label_46, 2, 4, 1, 1)
        self.label_47 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_47.setMinimumSize(QtCore.QSize(120, 150))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_2.addWidget(self.label_47, 2, 5, 1, 1)
        self.label_48 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_48.setMinimumSize(QtCore.QSize(120, 150))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_2.addWidget(self.label_48, 2, 6, 1, 1)
        self.label_49 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_49.setMinimumSize(QtCore.QSize(120, 150))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_2.addWidget(self.label_49, 2, 7, 1, 1)
        self.label_50 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_50.setMinimumSize(QtCore.QSize(120, 150))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_2.addWidget(self.label_50, 2, 8, 1, 1)
        self.label_51 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_51.setMinimumSize(QtCore.QSize(120, 150))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_2.addWidget(self.label_51, 2, 9, 1, 1)
        self.label_52 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_52.setMinimumSize(QtCore.QSize(120, 150))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_2.addWidget(self.label_52, 3, 0, 1, 1)
        self.label_53 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_53.setMinimumSize(QtCore.QSize(120, 150))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_2.addWidget(self.label_53, 3, 1, 1, 1)
        self.label_54 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_54.setMinimumSize(QtCore.QSize(120, 150))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.gridLayout_2.addWidget(self.label_54, 3, 2, 1, 1)
        self.label_55 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_55.setMinimumSize(QtCore.QSize(120, 150))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_2.addWidget(self.label_55, 3, 3, 1, 1)
        self.label_56 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_56.setMinimumSize(QtCore.QSize(120, 150))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_2.addWidget(self.label_56, 3, 4, 1, 1)
        self.label_57 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_57.setMinimumSize(QtCore.QSize(120, 150))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_2.addWidget(self.label_57, 3, 5, 1, 1)
        self.label_58 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_58.setMinimumSize(QtCore.QSize(120, 150))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_2.addWidget(self.label_58, 3, 6, 1, 1)
        self.label_59 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_59.setMinimumSize(QtCore.QSize(120, 150))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_2.addWidget(self.label_59, 3, 7, 1, 1)
        self.label_60 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_60.setMinimumSize(QtCore.QSize(120, 150))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_2.addWidget(self.label_60, 3, 8, 1, 1)
        self.label_61 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_61.setMinimumSize(QtCore.QSize(120, 150))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_2.addWidget(self.label_61, 3, 9, 1, 1)
        self.label_62 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_62.setMinimumSize(QtCore.QSize(120, 150))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_2.addWidget(self.label_62, 4, 0, 1, 1)
        self.label_63 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_63.setMinimumSize(QtCore.QSize(120, 150))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_2.addWidget(self.label_63, 4, 1, 1, 1)
        self.label_64 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_64.setMinimumSize(QtCore.QSize(120, 150))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.gridLayout_2.addWidget(self.label_64, 4, 2, 1, 1)
        self.label_65 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_65.setMinimumSize(QtCore.QSize(120, 150))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_2.addWidget(self.label_65, 4, 3, 1, 1)
        self.label_66 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_66.setMinimumSize(QtCore.QSize(120, 150))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_2.addWidget(self.label_66, 4, 4, 1, 1)
        self.label_67 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_67.setMinimumSize(QtCore.QSize(120, 150))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_2.addWidget(self.label_67, 4, 5, 1, 1)
        self.label_68 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_68.setMinimumSize(QtCore.QSize(120, 150))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_2.addWidget(self.label_68, 4, 6, 1, 1)
        self.label_69 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_69.setMinimumSize(QtCore.QSize(120, 150))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_2.addWidget(self.label_69, 4, 7, 1, 1)
        self.label_70 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_70.setMinimumSize(QtCore.QSize(120, 150))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_2.addWidget(self.label_70, 4, 8, 1, 1)
        self.label_71 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_71.setMinimumSize(QtCore.QSize(120, 150))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_2.addWidget(self.label_71, 4, 9, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea_2, 2, 1, 3, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_5.setText(_translate("MainWindow", "label_5", None))
        self.pushButton_8.setText(_translate("MainWindow", "top 10", None))
        self.pushButton_9.setText(_translate("MainWindow", "top 50", None))
        self.pushButton_10.setText(_translate("MainWindow", "top 100", None))
        self.pushButton_2.setText(_translate("MainWindow", "开始检索", None))
        self.pushButton_4.setText(_translate("MainWindow", "输出结果", None))
        self.pushButton_5.setText(_translate("MainWindow", "备用1", None))
        self.pushButton_6.setText(_translate("MainWindow", "备用2", None))
        self.lineEdit.setText(_translate("MainWindow", "图像路径", None))
        self.pushButton_3.setText(_translate("MainWindow", "打开图像", None))
        self.pushButton.setText(_translate("MainWindow", "选择图像库", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "1", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2", None))
        self.pushButton_7.setText(_translate("MainWindow", "选择算法", None))
        self.label_7.setText(_translate("MainWindow", "TextLabel", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.label_9.setText(_translate("MainWindow", "TextLabel", None))
        self.label_10.setText(_translate("MainWindow", "TextLabel", None))
        self.label_11.setText(_translate("MainWindow", "TextLabel", None))
        self.label_12.setText(_translate("MainWindow", "TextLabel", None))
        self.label_13.setText(_translate("MainWindow", "TextLabel", None))
        self.label_14.setText(_translate("MainWindow", "TextLabel", None))
        self.label_15.setText(_translate("MainWindow", "TextLabel", None))
        self.label_16.setText(_translate("MainWindow", "TextLabel", None))
        self.label_17.setText(_translate("MainWindow", "TextLabel", None))
        self.label_18.setText(_translate("MainWindow", "TextLabel", None))
        self.label_19.setText(_translate("MainWindow", "TextLabel", None))
        self.label_20.setText(_translate("MainWindow", "TextLabel", None))
        self.label_21.setText(_translate("MainWindow", "TextLabel", None))
        self.label_37.setText(_translate("MainWindow", "TextLabel", None))
        self.label_38.setText(_translate("MainWindow", "TextLabel", None))
        self.label_39.setText(_translate("MainWindow", "TextLabel", None))
        self.label_40.setText(_translate("MainWindow", "TextLabel", None))
        self.label_41.setText(_translate("MainWindow", "TextLabel", None))
        self.label_42.setText(_translate("MainWindow", "TextLabel", None))
        self.label_43.setText(_translate("MainWindow", "TextLabel", None))
        self.label_44.setText(_translate("MainWindow", "TextLabel", None))
        self.label_45.setText(_translate("MainWindow", "TextLabel", None))
        self.label_46.setText(_translate("MainWindow", "TextLabel", None))
        self.label_47.setText(_translate("MainWindow", "TextLabel", None))
        self.label_48.setText(_translate("MainWindow", "TextLabel", None))
        self.label_49.setText(_translate("MainWindow", "TextLabel", None))
        self.label_50.setText(_translate("MainWindow", "TextLabel", None))
        self.label_51.setText(_translate("MainWindow", "TextLabel", None))
        self.label_52.setText(_translate("MainWindow", "TextLabel", None))
        self.label_53.setText(_translate("MainWindow", "TextLabel", None))
        self.label_54.setText(_translate("MainWindow", "TextLabel", None))
        self.label_55.setText(_translate("MainWindow", "TextLabel", None))
        self.label_56.setText(_translate("MainWindow", "TextLabel", None))
        self.label_57.setText(_translate("MainWindow", "TextLabel", None))
        self.label_58.setText(_translate("MainWindow", "TextLabel", None))
        self.label_59.setText(_translate("MainWindow", "TextLabel", None))
        self.label_60.setText(_translate("MainWindow", "TextLabel", None))
        self.label_61.setText(_translate("MainWindow", "TextLabel", None))
        self.label_62.setText(_translate("MainWindow", "TextLabel", None))
        self.label_63.setText(_translate("MainWindow", "TextLabel", None))
        self.label_64.setText(_translate("MainWindow", "TextLabel", None))
        self.label_65.setText(_translate("MainWindow", "TextLabel", None))
        self.label_66.setText(_translate("MainWindow", "TextLabel", None))
        self.label_67.setText(_translate("MainWindow", "TextLabel", None))
        self.label_68.setText(_translate("MainWindow", "TextLabel", None))
        self.label_69.setText(_translate("MainWindow", "TextLabel", None))
        self.label_70.setText(_translate("MainWindow", "TextLabel", None))
        self.label_71.setText(_translate("MainWindow", "TextLabel", None))
        

import pic_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

